### ISSUE TITLE
Make Variation Filters optional

### ISSUE THREAD

**Issue by mendesgab** [alaarihan/woo-variations-table#1]
This plugin does almost exactly what I need – thank you.

However, my variation tables are small, and the variation filters just above the table are not needed or useful in the site I’m building. It would be good if there was a configuration option to disable them. 

What would be the best option to disable "keywords" and "type" fields without touching the files?

**Comment by alaarihan** [comment]
Thanks for reporting this, I think it's good idea to have an option to show/hide filters, I will work on that.

**Comment by alaarihan** [comment]
Fixed in v2.1.3
