### ISSUE TITLE
woo variations table not working with WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by romailshah** [alaarihan/woo-variations-table#15]
Hey! I am facing a weird issue with the woo variations table plugin. I am using WooCommerce Product Add-ons too, I wanted to display a variation table of products along with the Product Add-ons.

The Product Add-ons plugin is working perfect BUT when I installed and activated woo variations table plugin, the WooCommerce Product Add-ons fields disappeared. Now, whenever I disable woo variations table plugin, the WooCommerce Product Add-ons works. This is quite annoying. I want both of them to work at the same time.

Please provide a solution about this issue ASAP.

Thanks,
Romail

**Comment by alaarihan** [comment]
My plugin replace a part of the WooCommerce single product page so if any other plugin tried to add something or replace something on that part of the page then that won't work and we can't do anything about that in fact, we can only do custom coding to make it work with specific plugins and specific use cases.

**Comment by romailshah** [comment]
So, can you make it work with the plugin I mentioned?

**Comment by alaarihan** [comment]
Sorry, it needs custom coding and I don't have time right now, sorry again :(

**Comment by romailshah** [comment]
Alright.

Thank you. I’ll look for some other plugin then.
