### ISSUE TITLE
add to cart don't work

### ISSUE THREAD

**Issue by NoureSolutions** [alaarihan/woo-variations-table#2]
hello, first thank you for this plugin is very useful for my case, but I had some issues with :
- add to cart button which didn't work.
- also, i hope to change the order of columns but i cannot.
Can you tell me which file should i modify or verify to resolve this problem.
I hope have your answer as soon as possible 
thank you.

**Comment by alaarihan** [comment]
Hi,

Can you show me your page where "add to cart" button doesn't work please?

I'm working on this feature where you can reorder (sort) columns, right now it's not possible but if you want to change attributes sorting then you can do that by editing the product and change the order of the attributes as you need.

**Comment by NoureSolutions** [comment]
![FireShot Capture 009 - Clé à molette phosphatée BAHCO 90 – outizone - localhost](https://user-images.githubusercontent.com/61414122/75152500-79529980-5709-11ea-9d30-5335c6ccb787.png)
 
you find here the page of variable product that i need to insert the variations table in.
those buttons add to cart called ''ajouter au panier" .
Now you can see that the price is showing in the first position but I want to put it just before the last column.

**Comment by alaarihan** [comment]
I need to see what happens when I click "add to cart" button so if you can send me a link to see then I can check easier

**Comment by NoureSolutions** [comment]
ok wait plz i will do it on the server because it's just on localhost now

**Comment by NoureSolutions** [comment]
here you find the url : http://outizone.ejhtech.com/outizone/product/cle-a-molette-phosphatee-bahco-90/

**Comment by alaarihan** [comment]
As I see, your site has maintenance mode enabled, the plugin use WooCommerce api to add the item to cart using this url:
http://outizone.ejhtech.com/?wc-ajax=add_to_cart
but as you see, this url is not working in your site, you need to disable maintenance mode

**Comment by NoureSolutions** [comment]
the maintenance mode is already disabled, and the url of my home page is http://outizone.ejhtech.com/outizone

**Comment by alaarihan** [comment]
I've fixed the problem, and released v2.1.2 just now, please update and try it

**Comment by NoureSolutions** [comment]
thank you it's working fine now, can you tell me please which file should i modify to reorder the columns of table.

**Comment by alaarihan** [comment]
there are two files responsible for reordering columns if you want to modify them yourself..
App.svelte
Variation.svelte
And you need to do build after you modify them ( you need to have some knowledge in svelte and npm ) ..
HOWEVER I don't recommend doing that because when you update the plugin, all your changes will be overwritten, so I suggest you to wait until I implement this feature in the future release 2.3.0
