### ISSUE TITLE
Spanish - Argentina translation does not work

### ISSUE THREAD

**Issue by desarrollostello** [alaarihan/woo-variations-table#23]
Hello!! I try to translate the plugins with the Loco Translate plugins but it doesn't work. I try to move it, move it, but it always stays in the same place, in
"languages ​​/ plugins / woo-variations-table-en_AR.po", as much as I try to move it, because I had read some of that, but when I save and re-enter it is still there, it does not move, and on the web it continues to be seen in the original language.

**Comment by alaarihan** [comment]
Hi,

Try the latest release please, I've fixed this issue.
