### ISSUE TITLE
Min max quantity not working.

### ISSUE THREAD

**Issue by hardik7681** [alaarihan/woo-variations-table#3]
Hi,
Thanks for the excellent plugin, simple and easy to implement.
However, I am using store front theme and would like to implement the min/max quantity as well as step increase/decrease on the variations. I am using this plugin :- http://www.wpeliteplugins.com/downloads/woocommerce-minimum-maximum-quantities/
However its not working. Any thoughts here??

Thanks,
Hardik

**Comment by alaarihan** [comment]
Sorry this plugin can't be compatible with this other plugin
