### ISSUE TITLE
does not respect custom validation

### ISSUE THREAD

**Issue by ja-sk** [alaarihan/woo-variations-table#32]
First of all, great plugin, thanks!

Unfortunately the plugin does not seem to respect cart validations. We check if a product combination is allowed in the cart before adding the product to the cart. The Table plugin does not add the product in question but still shows the tick mark and pretends everything went fine. Is there a way to check if the produzct adding actually went through? Alternatively if there was a way to get a page reload instead of the Ajax adding. That should do the trick. 

Simplified version of our comparison for debug purposes:
      
      function so_validate_add_cart_item( $passed, $product_id, $quantity, $variation_id = '', $variations= '' ) {

        // do your validation, if not met switch $passed to false
        if ( 1 != 2 ){
            $passed = false;
        wc_add_notice( __( 'You can not do that', 'textdomain' ), 'error' );
        }
        return $passed;

    }
     add_filter( 'woocommerce_add_to_cart_validation', 'so_validate_add_cart_item', 10, 5 );

**Comment by alaarihan** [comment]
I think the problem has been fixed in the latest release, try it please.

**Comment by alaarihan** [comment]
Closing this
