### ISSUE TITLE
Issues with ajax and fly to cart

### ISSUE THREAD

**Issue by xblomx** [alaarihan/woo-variations-table#35]
There is a woocommerce event which is used in your plugin
$( document.body ).trigger( 'added_to_cart', [ response.fragments, response.cart_hash, $button ] );
The third parameter is supposed to be add to cart button as you can see above ( Copied from woocommerce file ).
But in your code, the third parameter is null.

Could you fix that?

**Comment by alaarihan** [comment]
Fixed in v2.2.7
