### ISSUE TITLE
Not showing in Edge

### ISSUE THREAD

**Issue by hoshigetsu** [alaarihan/woo-variations-table#4]
Table seems to disappear in Microsoft Edge. 

Getting this: 
![script-issue](https://user-images.githubusercontent.com/44241008/75558791-5b8a7a80-5a10-11ea-86cb-8f4ae18b5c73.png)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number

Have had a few customer's say about not being able to see options, have tested in Firefox, Chrome, and Edge. Works fine in both Firefox and Chrome.

**Comment by alaarihan** [comment]
Thanks for reporting this issue, I made some changes to make this plugin compatible with Edge browser, I have released v2.1.4, try it please and confirm.

**Comment by hoshigetsu** [comment]
That worked! It is working now in Edge 

> Thanks for reporting this issue, I made some changes to make this plugin compatible with Edge browser, I have released v2.1.4, try it please and confirm.
