### ISSUE TITLE
dismatch attribute ordering

### ISSUE THREAD

**Issue by Dravenrip** [alaarihan/woo-variations-table#40]
Hi guys !

I have a strange problem with woo-variations-table and the attributes for variables product.
Plugin seems to order differently the header table (TH) and the lines of my table.

In the header it seems to use the attribute slug order, and in table something else.

Is there a way to patch this ? 

here is a cap of my table : 
<img width="1681" alt="Capture d’écran 2021-02-12 à 15 33 13" src="https://user-images.githubusercontent.com/2520639/107780966-a5ff2700-6d47-11eb-8c3a-cb71e37c57a1.png">

**Comment by alaarihan** [comment]
Hi,

Please try v2.2.8, it fixes this issue.
