### ISSUE TITLE
Czech (cs_CZ) translation .po files

### ISSUE THREAD

**Issue by dancernohorsky** [alaarihan/woo-variations-table#41]
I enclose a translation into Czech in the attachments.
Best regards
Dan Cernohorsky
[woo-variations-table-cs_CZ.zip](https://github.com/alaarihan/woo-variations-table/files/5978070/woo-variations-table-cs_CZ.zip)

**Comment by alaarihan** [comment]
Thank you @dancernohorsky, your translation will be included in the next release.

Thanks again
