### ISSUE TITLE
Attribute text value instead of slug

### ISSUE THREAD

**Issue by SM7YSA** [alaarihan/woo-variations-table#43]
Love the plugin! But found an issue. When showing the attributes in a list, it shows the slug and not the text value of it. 

For example, in Sweden we have special characters thats not allowed in slugs and I want to show the color name "Grå" (grey) but instead it shows the customer the ugly slug "gra" which is very confusing. 
<img width="434" alt="Skärmavbild 2021-04-16 kl  09 22 19" src="https://user-images.githubusercontent.com/33499424/114987312-4fbc7a80-9e95-11eb-90c6-3db473822ada.png">

**Comment by alaarihan** [comment]
Thanks @SM7YSA , I just fixed the problem @v.2.2.9
