### ISSUE TITLE
Qty up/down arrow missing 

### ISSUE THREAD

**Issue by theaduo** [alaarihan/woo-variations-table#5]
I'm using a theme that I think modifies the qty up/down arrows so that they are +/- buttons, as you can see here in the theme demo page:
http://janstudio.net/claue/demo/product/analogue-resin-strap-watch/

When your excellent plugin is installed, unfortunately what happens is that there are neither up/down nor +/- buttons showing next to the qty. A user would have to type the amount in manually.

Is there something you can do to allow the default qty adjuster of the theme to work with your plugin?

**Comment by alaarihan** [comment]
Sorry this is not possible, we can't use the theme button in this plugin, you need to style the button to make it a little similar to what you need.

**Comment by theaduo** [comment]
Thanks. I'm guessing maybe the theme is using JS and CSS to remove the default up/down symbols and replace with plus/minus symbols which aren't showing when your plugin is installed for some reason.
