### ISSUE TITLE
Internet Explorer problem

### ISSUE THREAD

**Issue by SaerosCZ** [alaarihan/woo-variations-table#6]
Hello, 

I am using this great plugin in one of my B2B project, but I have new report from customers with older computers that IE doesnt show table of variations and cart.

I am using version WVT 2.1.4., WOO 3.9.3 (3.9.2 tested too), IE 

I tested it on the newest Chrome, FF, Edge everything is OK. But IE11

Idea: It would be great if we can using shortcode for using on individual pages too.

Thanks for a great work, Jan

**Comment by alaarihan** [comment]
Sorry about this, I use Svelte JS in this plugin and it doesn't support IE browser so I can not do any thing about that :(

**Comment by alaarihan** [comment]
Regarding your Idea, I will think about it, maybe it's better to add support for the official woocommerce blocks for gutenberg editor.

**Comment by SaerosCZ** [comment]
Thanks for info, H

**Comment by alaarihan** [comment]
Closing this

**Comment by dannio** [comment]
@alaarihan you can get this to work in IE if you compiled the code with babel and added polyfill like polyfill.js and bluebird.js.
