### ISSUE TITLE
Do not work with Elementor

### ISSUE THREAD

**Issue by zanozatm** [alaarihan/woo-variations-table#8]
When i use Elementor your plugin don`t work.
Any ideas how to make them friends?

**Comment by alaarihan** [comment]
Do you use some Elementor block to show the variable product or what is the problem exactly?

**Comment by zanozatm** [comment]
i use JET WOO BUILDER blocks. Default page works correctly - variations table is displayed, but not with Elementor page

**Comment by alaarihan** [comment]
Can you try to delete line 168 and line 173 from woo-variations-table/woo-variations-table.php file and try again?

I currently add the js code on the woocommerce single product pages only, so if you removed these lines I mentioned, it won't be restricted to them, so try that and tell me if it worked or not please.

**Comment by zanozatm** [comment]
It did not help, the table does not displayed. In console error in both cases
ReferenceError: wooVariationsTableData is not defined 
at main.js:6
at main.js:13

**Comment by miketosk** [comment]
Hello, I'm facing the same issue. I cannot display the variation table on Elementor (single product page - type variable). Any news / advice? Thanks a lot.

**Comment by alaarihan** [comment]
in your case with Elementor it's using custom coded block to display the product and that is not standard for all templates so I can't do anything about that, you need to use WooCommerce product single page to make this plugin work or custom coding.
