### ISSUE TITLE
shortcode to integrate the table in specific div

### ISSUE THREAD

**Issue by NoureSolutions** [alaarihan/woo-variations-table#9]
hello, 
thank you for this great module, can we use a shortcode to facilitate the integration of the table anywhere on the page?
because i need to insert the table to hidden zone after the description.
thank you again.
best regards!

**Comment by alaarihan** [comment]
Hi,
I'm thinking about building a Gutenberg block and shortcode to make it possible to place the table anywhere in any page, will see about that..

**Comment by NoureSolutions** [comment]
yes of course with this it will be more efficient so i'm waiting for this. another thing it about the price row in the table, it showed on the first row before the attributes. Normally the price should be after attributes and before quantity row.

**Comment by alaarihan** [comment]
> Normally the price should be after attributes and before quantity row.
Yes, you are right, I moved it to before quantity column, just update to the latest release to get it and thanks for the notice :)

**Comment by alaarihan** [comment]
Now it's possible to sort the columns as you wish from settings page :) just update to 2.2 release
